apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aleena-vqa-pvc
spec:
  storageClassName: rook-cephfs 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
